global:
  scrape_interval: 10s

scrape_configs:

  - job_name: "docker-engine"
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: "metrics-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["metrics_exporter:8000"]

  - job_name: "elasticsearch"
    metrics_path: /_prometheus/metrics  # Only if you set up a Prometheus exporter
    static_configs:
      - targets: ["elasticsearch:9200"]

  - job_name: "logstash"  # Optional: if instrumented
    static_configs:
      - targets: ["logstash:9600"]
